<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/css/home-style.css">
    <link rel="icon" href="/assets/icon-for-site.png">
    <title>Starter Page</title>
</head>
<body>
<div class="container-home">
    <div class="col-1">
        <img src="/assets/welcome.svg" alt="">
    </div>
    <div class="col-2">
        <div class="title-block">
            <h1 class="title"><b>Welcome!</b>
                <br>
                This is a modern messenger - a night owl</h1>
        </div>
        <div class="btn_block">
            <a href="/signIn" class="btn">
                <span class="btn_text">
                    LogIn
                </span>
            </a>
            <a href="/signUp" class="btn">
                <span class="btn_text">
                    SignUp
                </span>
            </a>
        </div>
    </div>

</div>
</body>
</html>
